-- Schema da Demo v1, igual ao que o Hibernate gerava com ddl-auto=update.
-- Bancos que já têm essas tabelas (volume da v1) são marcados como V1 pelo
-- baseline do Flyway e recebem apenas as migrações seguintes.

CREATE TABLE categorias (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome      VARCHAR(255) NOT NULL,
    tipo      VARCHAR(255) NOT NULL,
    eh_padrao BOOLEAN      NOT NULL,
    CONSTRAINT categorias_tipo_check CHECK (tipo IN ('RECEITA', 'DESPESA'))
);

CREATE TABLE transacoes (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- RNF05: valor monetário exato, nunca FLOAT/DOUBLE
    valor        NUMERIC(19, 2) NOT NULL,
    tipo         VARCHAR(255)   NOT NULL,
    data         DATE           NOT NULL,
    descricao    VARCHAR(255),
    categoria_id BIGINT         NOT NULL,
    CONSTRAINT transacoes_tipo_check CHECK (tipo IN ('RECEITA', 'DESPESA')),
    CONSTRAINT fk_transacoes_categoria FOREIGN KEY (categoria_id) REFERENCES categorias (id)
);
